.ss 12 0
.de BP
.IP "\\fB\\$*"
..
.hw areas
.
.TH audiomoth 1 "FEB 2021" AudioMoth "User Manuals"
.SH "NAME"
audiomoth \- command-line interface to the AudioMoth acoustic logger
.
.SH "SYNOPSIS"
.
.B audiomoth
.RB [ --uid
.IR uid ]
.RB [ \-i ]
.br
.B audiomoth
.RB [ --uid
.IR uid ]
.B \-T
.br
.B audiomoth
.RB [ --uid
.IR uid ]
.RI [ configuration\ options
\&...]
.br
.B audiomoth --help
.br
.B audiomoth --version
.
.SH "DESCRIPTION"
.
The
.B AudioMoth
is an acoustic logger for outdoors use from
.IR "Open Acoustic Devices" .
This utility lets you configure an AudioMoth and set its clock
\- like the official utilities,
but without pulling in the whole
.I Node.js
and
.I React.js
ecosystems,
.\" "Ecosystem" may be too polite a word ...
and without a GUI.
.\" And without the phone-home feature.
.\" I.e. the HTTP calls in versionChecker.js.  Do people accept such
.\" things nowadays?
.PP
.BR audiomoth (1)
has three basic operations:
.IP \- 3x
.PD 0
Show the device's
.IR "time" ,
.IR "battery level" ,
.I  "identifier"
and
.IR "firmware version" .
.IP \-
Set the device's clock.
This is a common operation, since the AudioMoth loses time when you
replace the batteries.
.IP \-
Configure the device.
.PD
.PP
It cannot be used to upgrade the firmware.
Nor can it
.I show
the current configuration, e.g. recording schedule and gain.
.
.
.SH "OPTIONS"
.
.BP "\-i"
Show the device's
.IR "time" ,
.IR "battery level" ,
.I  "identifier"
and
.IR "firmware version" ,
i.e. everything except the configuration.
This is also what happens when you run it without arguments.
The output looks something like this:
.
.IP
.ft CW
.nf
time:     2022-01-07 11:14:58 +0100
battery:  4.1V
uid:      248d:9b02:6037:b5fe
firmware: AudioMoth-Firmware-Basic
version:  1.5.0
.fi
.
.BP "\-T"
Set the clock from the computer's clock.
The AudioMoth clock has a one second resolution, and unlike the
official utilities, this one doesn't try to get more accuracy by
waiting until the second flips over.
Thus the clock can be slightly more than one second off.
.
.BP "--uid \fInnnn:nnnn:nnnn:nnnn"
Refuse to do anything unless the device has a certain
.IR uid .
In particular, refuse to configure it.
This is useful if you have multiple devices for different purposes,
and don't want to mix up their configurations.
.
.BP "--help"
Print a brief help text and exit.
.
.BP "--version"
Print version information and exit.
.
.
.SS "Configuration options"
.
Configuration is, for better or worse, total rather than incremental.
You cannot e.g. change the time schedule without also deciding the sample rate
and everything else.
There are sane defaults for many things, though.
.PP
Some of the options are hard to explain without referring to the official
documentation, which also describes the physical interfaces (the
.SM USB/OFF/CUSTOM/DEFAULT
switch, the LEDs) and the naming of recording files.
.
.BP "\-t \fIhh:mm\-hh:mm"
Add a recording period, for example
.I 04:30\-07:00
or
.IR 22:00\-03:00 .
The device has room for five periods, but a period spanning midnight
counts as two.
.BP "\-t \fIhh:mm+duration"
The same, but with the period length (as minutes or hours and minutes)
instead of the end time:
.I 04:30\-07:00
can also be expressed as
.I 04:30\+2:30
or
.IR 04:30\+150 .
.
.BP "--time \fR..."
Synonym for
.BR \-t ,
for people who like longer names.
.
.BP "--cyclic \fIsleep+record"
Set up sleep/record cyclic recording. When the device would otherwise have
recorded continously, it instead sleeps for
.I sleep
seconds, records for
.I record
seconds, and so on.
It's a way to sample a soundscape, I guess you could say.
.IP
Note the order: the sleep time is given
.IR first ,
so that e.g.
.I 50+10
records for 10 seconds every minute.
.
.BP "--dates \fIfirst--last"
Record only during the specified dates.
Dates are given in ISO format with a double
.B --
between. For example,
.I 2022-01-16--2022-01-31
spans from the start of January, 16 to the end of January.
.
.BP "--dates \fIfirst+days"
As above, but specify a number of days rather than the last day.
For example,
.IR 2022-01-16+16 .
.
.BP "--gain \-2\fR|\fP\-1\fR|\fP0\fR|\fP\+1\fR|\fP\+2"
The gain level, from
.B \-2
(low) to
.B +2
(loud). Default:
.BR 0 .
.
.BP "--rate 8\fR|\fP16\fR|\fP32\fR|\fP48\fR|\fP96\fR|\fP192\fR|\fP250\fR|\fP384 \fR[\fPkHz\fR]"
The sampling rate. Default:
.BR 48kHz .
.
.PP
The high-, low- and band-pass filters are mutually exclusive: you can choose one,
or of course skip filtering entirely.
.
.BP "--highpass \fIfreq"
Enable the
.IR "high-pass filter" ,
i.e. record only high-frequency sounds.
Useful for recording bats, presumably.
You can specify the frequency with and without decimals, and give the unit as
.B kHz
or
.B Hz
(default if you say nothing):
.BR 18000 ,
.BR 18000Hz ,
.B 18kHz
and
.B 18.0kHz
mean the same thing.
.
.BP "--lowpass \fIfreq"
Enable the
.I "low-pass"
filter: record only lower-frequency sounds.
.
.BP "--bandpass \fIfreq\fR\-\fIfreq"
Enable the
.I "band-pass"
filter: record in a specific frequency band.
.
.PP
.I "Amplitude threshold"
or
.I "amplitude-triggered"
recording means recording only during and soon after loud sounds,
like bat calls or gunshots.
(A bat call would probably also need a high-pass filter.)
These recordings are saved in a special file format:
neither individual files nor one long file with silent periods.
.
.BP "--trigger \fIamplitude\fP%"
Set the trigger or threshold to a certain percentage of max amplitude.
Valid values are from
.B 0%
to
.BR 100% ,
without fractions.
.IP
It is a bit unclear what 50% means, and the official tool also supports
specifying the threshold as a raw amplitude or in dB.
Whatever it means, 50% should be equivalent to placing the official slider
in the middle of its range.
.
.BP "--duration \fIseconds"
Record for at least
.I seconds
after an amplitude trigger.
You can specify 0\-60 seconds, and there is no default: if you enable
triggered recording you have to choose a duration.
.
.BP "--elephants"
Disable the filter which removes very low frequency buzz.
This is supposedly useful when recording elephants.
.
.BP "--need-chime"
In
.SM CUSTOM
mode, don't start the recording program
until the device has heard the chime from some smartphone app.
.
.BP "--energy-saver"
Trade some (not much, apparently) audio quality for longer battery life:
around 30\-40% better.
At sampling rates above 48\|kHz there are no savings.
.
.BP "--ignore-low-battery"
Keep recording when the battery runs low.
This can cause corrupted recordings
(but it's unclear whether anyone knows how high the risk is).
.
.BP "--NiMH\fR, \fP--LiPo\fR, \fP--alkaline"
The battery type.  This only affects the battery level indication and,
as far as I can tell, specifically the flashing LEDs.
NiMH and LiPo are, for these purposes, the same thing.
Default:
.BR --alkaline .
.
.BP "--no-rw-led\fR, \fP--no-battery-led"
Disable the LED flashing which indicates if the device is recording or waiting to record,
or, disable the flashing which indicates battery level.
.
.
.SH "EXIT STATUS"
.
Non-zero on failure.
.
.
.SH "COMPARED TO THE OFFICIAL TOOL"
.
The official AudioMoth configuration tool has a JSON-based configuration file format.
.BR audiomoth (1)
cannot read such files, but it's useful to see how command-line options map to them,
since they summarize everything that can be officially configured.
.
.PP
.PD 0
.
.IP "timePeriods" 26x
.B \-t
.
.IP "sampleRateIndex"
.B --rate
.IP "sampleRate"
--rate
.IP "gainIndex"
.B --gain
.IP "gain"
--gain
.
.IP "recDuration"
.B --cyclic
.IP "recordDuration"
--cyclic
.IP "sleepDuration"
--cyclic
.
.IP "localTime"
.
.IP "dutyEnabled"
--cyclic
.IP "firstRecordingDate"
.B --dates
.IP "lastRecordingDate"
--dates
.
.IP "passFiltersEnabled"
.BR --highpass ", " --lowpass ", " --bandpass
.IP "filterType"
--highpass, --lowpass, --bandpass
.IP "lowerFilter"
--highpass, --lowpass, --bandpass
.IP "higherFilter"
--highpass, --lowpass, --bandpass
.
.IP "amplitudeThresholdingEnabled"
.B --trigger
.IP "amplitudeThreshold"
.IP "amplitudeThresholdingScale"
.IP "minimumAmplitudeThresholdDuration"
.B --duration
.
.IP "version"
not used
.IP "displayVoltageRange"
.BR --NiMH ", " --LiPo ", " --alkaline
.IP "requireAcousticConfig"
.B --need-chime
.IP "ledEnabled"
.BR --no-rw-led \ (inverted)
.IP "batteryCheckEnabled"
apparently a legacy name for lowVoltageCutoffEnabled
.IP "lowVoltageCutoffEnabled"
.BR --ignore-low-battery \ (inverted)
.IP "batteryLevelCheckEnabled"
.BR --no-battery-led \ (inverted)
.IP "energySaverModeEnabled"
.B --energy-saver
.IP "disable48DCFilter"
.B --elephants
.
.PD
.
.
.SH "BUGS"
.
.IP \- 3x
The official utility shows projected battery lifetime based on sampling rate
and other settings.  This one does not, although it may be vital information to
some users. When should I drive the 200 kilometers to switch batteries?
For how long can I record every morning, if I want to cover all of June?
.
.IP \-
.I "Amplitude threshold recording"
\- letting loud or distinct sounds start the recording \-
is still unsupported.
.
.IP \-
Anything having to do with time zones is unsupported:
.BR audiomoth (1)
configures the device to use UTC, also known as GMT.
It's a bit unclear how configuring a time zone affects the device;
possible areas include file names and file timestamps,
the recording periods and the recording dates.
That may be fixed eventually, but for now you have to plan recordings
in terms of UTC.
.
.IP \-
As mentioned above,
it would have been useful if you could list the current configuration of a device,
and modify only selected parameters.
It is unclear if this is technically possible.
.
.IP \-
It is unclear how to handle multiple devices attached to one computer;
The official utilities pick the first listed on the USB bus,
and so does this one.
.
.
.SH "AUTHOR"
.
J\(:orgen Grahn
.IR \[fo]grahn@snipabacken.se\[fc] .
.PP
.BR audiomoth (1)
uses
.B libhidapi
for USB access, and is (since there appears to be no firmware API documentation)
based on the
.I "Open Acoustic Devices"
Javascript and C code:
Configuration-App,
HID,
USB-HID-Tool
and
Firmware-Basic.
.
.SH "LICENSE"
The GNU General Public License (GPL) version 2 or (at your option) version 3.
.
.SH "SEE ALSO"
.
.IR "The AudioMoth Operation Manual" .
Open Acoustic Devices, July 2021.
.br
.IR \[fo]https://www.openacousticdevices.info/audiomoth\[fc] .
.
.
.ig

galium:git/audiomoth% lsusb
Bus 002 Device 005: ID 10c4:0002 Silicon Labs F32x USBXpress Device
...

# ./usbhidtool 0x10C4 0x0002 0x00 0x01
  01 2b 00 ... [64]

01 5b da 30 00 ... [64]

# ./usbhidtool 0x10C4 0x0002 0x00 0x04
  01 2b 00 ... [64]

04 06 00 ... [64]

# ./usbhidtool 0x10C4 0x0002 0x00 0x03
  01 2b 00 ... [64]

03 fe b5 37 60 02 9b 8d 24 00 ... [64]

# ./usbhidtool 0x10C4 0x0002 0x00 0x08
  01 2b 00 ... [64]

08 41 75 64 69 6f 4d 6f 74 68 2d 46 69 72 6d 77 61 72 65 2d 42 61 73 69 63 00 ... [64]
AudioMoth-...ic

# ./usbhidtool 0x10C4 0x0002 0x00 0x05
  0 0 0 0 ... [64]

05 a2 cb 31 00 fe b5 37 60 02 9b 8d 24 06 01 05
00 41 75 64 69 6f 4d 6f 74 68 2d 46 69 72 6d 77
61 72 65 2d 42 61 73 69 63 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

..
